### ISSUE TITLE
Missing permissions/slots

### ISSUE THREAD

**Issue by hofst** [home-assistant-snap/home-assistant-snap#1]
Hi,

First: Thank you for providing the homeassistant snap, it is great having!
Unfortunately, I'm forced to install the snap in devmode which is cumbersome since (among other things) it doesn't automatically update.
The reason for that is that the snap appears to miss some slots for my integrations. E.g., raw usb access (for my weather station), raw serial port access (for my leds), raw network access (for wake on lan).
Could you add those snap slots?

**Comment by jmgiaever** [comment]
Hi,Thanks for the feedback. Raw-usb is supported. However not automatically connected. You can connect it with ```sudo snap connect home-assistant-snap:raw-usb```I can also add `serial-port` interface, but can you give me the exact name of the network interface you'll need? You can find all og them under interfaces in the Snapcraft.io docs.

**Comment by hofst** [comment]
Thank you!
Last time I disabled devmode, it broke some things, so I just ordered another sd-card to experiment and disable it. I will let you know soon!

**Comment by jmgiaever** [comment]
I've pushed an update with «serial-port» support and it's building now. But I'll have to figure out which network interface that is needed for WOL. I'll keep you posted. :)

**Comment by hofst** [comment]
OK, I'm now prepared with backups :-) 
Did I see it correctly that you didn't push that new version to the snapstore yet?
I assume I need to build/install it manually?

**Comment by jmgiaever** [comment]
Hi,

Sorry, but I'm having some [problems with the remote builds lately](https://forum.snapcraft.io/t/problems-with-remote-build/24373) and can't figure out what the problem is. 

However, the package for the architecture amd64, ppc64el and armhf in the edge channel should have the serial-port plug, but the arm64 build failed for unknown reasons - and I haven't been able to build anything successfully after.

Hoping for a solution soon. (Just now trying to build v2021.5.3 - fingers crossed)

**Comment by hofst** [comment]
Oh, I see!
*fingers crossed*

**Comment by hofst** [comment]
FYI, I also had some snap-store connections issues yesterday. The culprit is most likely that yesterday, they finally resolved the Ubuntu 21.04 ship-blocker and publicly released it. The 21.04 downloads apparently affected the snap store availability. Maybe you just need to retry publishing today?

**Comment by jmgiaever** [comment]
Hi again,

It looks like [the issue I had](https://forum.snapcraft.io/t/problems-with-remote-build/24373/5?u=joachimmg) was related to freesms and that [it's picked up by the core developers](https://github.com/home-assistant/core/pull/50853) few hours ago. Seems like the [fix will come with v21.5.5](https://github.com/home-assistant/core/pull/50862).

**Comment by hofst** [comment]
sounds good, thank you!

**Comment by jmgiaever** [comment]
Hi,

HA 2021.5.5 is now out for amd64, arm64, ppc64el is now out and armhf is still compiling. They're found in the `latest/stable`-channel.

**Comment by jmgiaever** [comment]
Hi, the build for every architecture should be out now. :)

**Comment by hofst** [comment]
@jmgiaever thank you! I installed it and usb devices now work after manually connection the plugs.

However the network plug is still missing:
The log shows:
- `2021-05-20 20:11:49 ERROR (MainThread) [homeassistant.components.dhcp] Cannot watch for dhcp packets: [Errno 13] Permission denied`
- PermissionError: [Errno 13] Permission denied: 'ping'

The snap documentation is not very sophisticated but I assume you'd need to add the `network-observe` connection to the snap. 
I think for ping, you may also need to add an extra binary? https://github.com/orf/gping/issues/41

Could you do that?

**Comment by jmgiaever** [comment]
Hi,Yes. I haven't added any network plugs as I don't want to bloat the package with unnecessary plugs. I'll consult someone what i might add, or you can give me an example what you're using (e.g which component) and I'll figure it out. // Joachim

**Comment by hofst** [comment]
@jmgiaever 
Sure, thank you!
I'm using the modules:
- https://www.home-assistant.io/integrations/wake_on_lan/
- and the fritz box presence detection: https://www.home-assistant.io/integrations/fritz/

**Comment by jmgiaever** [comment]
Could you be kind and install `snappy-debug` on the device (`sudo snap install snappy-debug`) and run the following command to see which plugs it recommends:

```
sudo journalctl --output=short --follow --all | sudo snappy-debug
```

**Comment by hofst** [comment]
Ha, I already mostly guessed the right steps:

= AppArmor =
Time: Apr 19 01:54:50
Log: apparmor="ALLOWED" operation="exec" profile="snap.home-assistant-snap.home-assistant-snap" name="/usr/bin/ping" pid=2932721 comm="python3" requested_mask="x" denied_mask="x" fsuid=0 ouid=0 target="snap.home-assistant-snap.home-assistant-snap//null->
File: /usr/bin/ping (exec)
Suggestions:
* adjust snap to ship 'ping'
* adjust program to use relative paths if the snap already ships 'ping'
* add one of 'firewall-control, network-control, network-observe' to 'plugs'


Don't really understand the following suggestions, though:

= AppArmor =
Time: Apr 19 01:50:50
Log: apparmor="ALLOWED" operation="open" profile="snap.home-assistant-snap.home-assistant-snap//null-/usr/bin/ping" name="/etc/ld.so.cache" pid=2931817 comm="ping" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /etc/ld.so.cache (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'system-files (see https://forum.snapcraft.io/t/the-system-files-interface for acceptance criteria)' to 'plugs'

thank you!

**Comment by jmgiaever** [comment]
> `Log: apparmor="ALLOWED" operation="open" profile="snap.home-assistant-snap.home-assistant-snap//null-`**/usr/bin/ping**`" name="/etc/ld.so.cache" pid=2931817 comm="ping" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

Looks like its trying to use `ping` and it's not shipped with the snap. This is something that I can add to the `home-assistant-toolbox`. I'll put it on the list as I need to add something more to it :)

**Comment by jmgiaever** [comment]
PS! I've pushed a new build with `network-observe` plug. It should be available within few hours in the `latest/edge` channel.

**Comment by hofst** [comment]
Great, thank you!

I updated and was confused at first: Even after plugging all connectors, I still saw some error messages in the homeassistant log, e.g., 
`2021-05-22 08:57:23 ERROR (MainThread) [homeassistant.components.dhcp] Cannot watch for dhcp packets: [Errno 13] Permission denied`
```PermissionError: [Errno 13] Permission denied: 'ping'```


But when I came back after a couple of hours, everything seems to work including "presence detection" and "wake on lan". Maybe the errors were from some cached state.

In any case, thanks a lot and I felt free to use your donation button ;-)

**Comment by jmgiaever** [comment]
Hi,That looks like the missing "ping" that i mentioned previously. I'll add it to the toolbox, but the upcoming week. 🤗Thank you so much for the donation. Joachim

**Comment by hofst** [comment]
I also took another dive into the dhcp error message:

```
ERROR (MainThread) [homeassistant.components.dhcp]
```

Since this is a default built-in feature of homeassistant (see [here](https://www.home-assistant.io/integrations/dhcp/)), this should reproduce on your machine as well if you check the homeassistant logs directly after startup. snappy-debug shows the following:

```
= AppArmor =
Time: May 24 19:23:12
Log: apparmor="ALLOWED" operation="create" profile="snap.home-assistant-snap.home-assistant-snap" pid=1274141 comm="python3" family="packet" sock_type="raw" protocol=768 requested_mask="create" denied_mask="create"

= AppArmor =
Time: May 24 19:23:12
Log: apparmor="ALLOWED" operation="capable" profile="snap.home-assistant-snap.home-assistant-snap" pid=1274141 comm="python3" capability=13  capname="net_raw"
Capability: net_raw
Suggestions:
* adjust program to not require 'CAP_NET_RAW' (see 'man 7 capabilities')
* add one of 'firewall-control, network-control, network-observe' to 'plugs'
* do nothing if program otherwise works properly
```

I checked and it seems like you need to have the "**network-control**" permission to create raw sockets on top of "**network-observe**".

**Comment by jmgiaever** [comment]
Hi,

No I'm not seeing this, but I'm also not using the default config, so dhcp hasn't been enabled by default in my installation. 

I've pushed an update with the network-control plug, hope it solves your issue. It should be available within some hours. 

Could you also try to un-plug `network-observe` while using `network-control`, to see if network-observe now is obsolete? Since DHCP is enabled by default and need a higher level plug, I would guess observe is unnecessary?

**Comment by hofst** [comment]
Thanks a lot! Here are the results:

- The log shows one more error. Since I have enabled devmode, I'm not sure if it is related to the AppArmor event. I would assume that in devmode, all permissions are granted.
```
2021-05-25 15:23:28 ERROR (SyncWorker_2) [scapy.runtime] Cannot set filter: libpcap is not available. Cannot compile filter !
2021-05-25 15:23:31 ERROR (MainThread) [homeassistant.components.dhcp] Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter !
```

- And snappy-debug points to a single remaining access violation: 
```
= AppArmor =
Time: May 25 15:30:08
Log: apparmor="ALLOWED" operation="open" profile="snap.home-assistant-snap.home-assistant-snap" name="/etc/ethertypes" pid=1545449 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /etc/ethertypes (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'system-files (see https://forum.snapcraft.io/t/the-system-files-interface for acceptance criteria)' to 'plugs'
*
```

- It does not seem to make a difference whether `network-observe` is enabled on top of `network-control` so I guess it is save to remove it again.

No worries if you don't feel like fixing this. My main use cases are covered, so I'm already happy :-)

**Comment by jmgiaever** [comment]
I'll try add `libpcap0.8`, the file `/etc/ethertypes` also looks to be a part of `libpcap`.

**Comment by jmgiaever** [comment]
Hi, I think I've solve the issue around this:
```
2021-05-25 15:23:28 ERROR (SyncWorker_2) [scapy.runtime] Cannot set filter: libpcap is not available. Cannot compile filter !
2021-05-25 15:23:31 ERROR (MainThread) [homeassistant.components.dhcp] Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter !
```

I'm pushing a new version to the channel `latest/edge`. It will be promoted to channel `2021.7` in a day or so.

**Comment by hofst** [comment]
Ho Joachim,
Thank you! I will try it once I get back home next week

**Comment by jmgiaever** [comment]
Ugh,

Seems like the issue still persist on `arm*` devices, but not on 
`amd64`. I'll have to dig deeper into the issue.

Med vennlig hilsen / Best regards

*Joachim M. Giæver*



giaever.online ***@***.*** 
***@***.***>+47 45 00 46 10 <tel:+4745004610>

**Comment by hofst** [comment]
Good to know! I'm running it on a RaspberryPi4 (arm64)

**Comment by jmgiaever** [comment]
Ok, give it a try and let me know if itr's just me. Find it strange that it doesn't happen on `amd` only `arm` (havent tried 32 `hf` though).

**Comment by hofst** [comment]
I updated and there seems to be only one problem left. I currently get the following from snap-debug:
```
= AppArmor =
Time: Aug 14 11:19:11
Log: apparmor="DENIED" operation="open" profile="snap.home-assistant-snap.home-assistant-snap" name="/etc/ethertypes" pid=2767905 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /etc/ethertypes (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'system-files (see https://forum.snapcraft.io/t/the-system-files-interface for acceptance criteria)' to 'plugs'
```

and in the logs I see the following error (likely related):
```
2021-08-14 11:19:31 WARNING (MainThread) [zeroconf] Error with socket 22 (('2003:ec:9706:bf00:dea6:32ff:fe19:5b', 5353, 0, 0))): [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1048, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network is unreachable
```

**Comment by jmgiaever** [comment]
Hi,

which release track are you on? `latest/stable`? Check with

```
snap info home-assistant-snap | grep "tracking:"
```

**Comment by jmgiaever** [comment]
I'm not getting this on neither `amd64` or `arm64`... :thinking: 

```
2021-08-14 11:19:31 WARNING (MainThread) [zeroconf] Error with socket 22 (('2003:ec:9706:bf00:dea6:32ff:fe19:5b', 5353, 0, 0))): [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1048, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network is unreachable
```

Does it happen frequently or only upon start-up? I can see it's an IPv6, which I do not have enabled on my local network. Could it be a bug with HA Core?

**Comment by hofst** [comment]
- I'm on `latest/stable` - it looked like the most current version and appears to have the same version as `latest/edge` (2021.8.6). Should I switch to `latest/edge`?
- I'm using Ubuntu 21.04 on a RaspberryPi4 with your snap HomeAssistant and almost no other configuration changes to the OS. Could it be caused by a HomeAssistant plugin? It only occurs during startup. Since there is a simultaneous `apparmor denied` event, it could be caused by a missing snap permission. Or the two events cold be unrelated. It's strange.

**Comment by jmgiaever** [comment]
Hi,I'm trying not find out which package to add to get the "ether types" file included. I might just copy it in and see if that leads to a better explanation to the error.

**Comment by hofst** [comment]
thank you!

**Comment by jmgiaever** [comment]
Yay, `netbase` was the package missing. New version pushed now. Should be available in few hours.

**Comment by hofst** [comment]
Great! I just tried it out via `latest/edge` and there is no error anymore (neither from apparmor in the journal nor in the homeassistant log) :-) 

Kudos! 

I made another donation to you via paypal!

**Comment by jmgiaever** [comment]
Thank you very much! :) Appreciated. 

I'm still having the `libpcap` issue on `arm64`, but I'm on Ubuntu Core and not Ubuntu Server (which I guess you are using?), and there might be some differences. (You're not running it using classic confinement?)

// J

**Comment by hofst** [comment]
Yes, I use Ubuntu Server (which may make a difference) and I use the default `strict` confinement

**Comment by jmgiaever** [comment]
Hi, Thank! 

Don't mean to bother you, and do not feel obligated to do this, but if you have the chance. I will highly appreciate it. 

You're also using the `arm64` pacakage, but on a differen OS. Comparing this with the amd64 package on my computer I get different results.

Anyway, if you can check for the libpcap:

Login to the home-assistant-snap shell:

```bash
sudo snap run --shell home-assistant-snap
```

Go into the `$SNAP` dir and activate venv.

```bash
$ cd $SNAP
$ source bin/activate
```

Go into the Python intepreter and check the output of the function `find_library`:

```bash
$ python3
```

and in the intepreter do

```
>>> from ctypes.util import find_library
>>> print(find_library('pcap') # just pcap, not libpcap
```
(do not write `>>>`)

Does it say *«None»* or *«libpcap.so.0.8»*? I get the latter as an output on amd64. The first on arm64 :/

(You can now exit python by typing `exit()`, then write `deactivate` to end the venv and `exit` to exit the shell)

**Comment by hofst** [comment]
I get `libpcap.so.0.8`.
However, I may have installed some related packages in my Ubuntu that could leak into the snap:
I found the following command in my bash history:
`sudo apt install tcpdump libpcap-dev`

**Comment by jmgiaever** [comment]
Thank you very much! :)

They should't, as you're running in the confined environment. 

I find all the files in my environment too, and it is in the `LD_LIBRARY_PATH` that `ctypes.util.find_library` should fall back to. But.... it returns `None`.

Seems like I need to boot up another b RPi after all, with an Ubuntu Server OS, to debug from there too. 

Where do I donate money back? :1st_place_medal:

**Comment by hofst** [comment]
> Where do I donate money back? 🥇

I'm happy if you stay motivated and keep maintaining this awesome snap for a long time :-)

**Comment by jmgiaever** [comment]
I'll do my best! Thank you for your help and patience.

**Comment by jmgiaever** [comment]
NB! I've verified that it's not using the system packages from apt. Installed the Ubuntu Server distro, removed (+purged) both tcpdump and libpcap, and it works on `armhf`. So it must be Ubuntu Core specific.
