### ISSUE TITLE
[Errno 13] Permission denied with InfluxDB integration

### ISSUE THREAD

**Issue by elwin1234** [home-assistant-snap/home-assistant-snap#12]
Hi!

First of all: great thanks to your for actively maintaining this snap.

I had an issue with getting [the InfluxDB integration](https://www.home-assistant.io/integrations/influxdb/) to work. The error in the logs is:

```
[homeassistant.components.influxdb] Cannot connect to InfluxDB due to '[Errno 13] Permission denied'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible.
```
The error is triggered at the moment the integration tries to perform an http call. For example at https://github.com/home-assistant/core/blob/c1967abfca3e6a55fe330afea6a6da9a3b59f409/homeassistant/components/influxdb/__init__.py#L361. 

After some debugging with `snappy-debug` [and some Googling](https://forum.snapcraft.io/t/solved-python-multitasking-strict-app-fails-semaphore/11325) it might be related to the combination of snap and Python’s multiprocessing module. I managed to get it to work [by using snapcraft-preload](https://github.com/sergiusens/snapcraft-preload). If you're interested I can create a PR.

**Comment by jmgiaever** [comment]
Hi,

Thanks for taking your time to investigate. I guess this can be related to the other issue that is open regarding MQTT (which I haven't had time to investigate further yet). #10

PR is more than welcome. 😄
