### ISSUE TITLE
Armhf latest stable not updated

### ISSUE THREAD

**Issue by silamon** [home-assistant-snap/home-assistant-snap#15]
The latest stable version of the home-assistant-snap for armhf is 
<html>
<body>

latest/stable | 2021.12.3 | 27 December 2021
-- | -- | --

</body>
</html>

Would it be possible to have a newer version published to the snap store? Thank you!

**Comment by jmgiaever** [comment]
Hi,

Unfortunately, the build system for the snaps are now longer able to build the snap. The armhf builders are running out of memory and the build crashes. 

It's unfortunately nothing we can do with it, as it's maintained by Canonical.
