### ISSUE TITLE
Bluetooth support / bluepy

### ISSUE THREAD

**Issue by jrohde** [home-assistant-snap/home-assistant-snap#2]
Hi Joachim,

Just starting with HA and with this snap everything was set up in seconds on my Ubuntu server running on a NUC. Awesome stuff, thanks very much!

There's only one thing i can't do at the moment and that's adding MiFlora Bluetooth (LE) devices (https://www.home-assistant.io/integrations/miflora/). It seems a package called bluepy is missing. I think this is something that needs to be added to snap?! Or can i fix this myself somehow?

**Comment by jmgiaever** [comment]
Hi,Every python module needed should be included in the `requirement.txt` file of the core. Do you have a log dump that you can attach? Can you also check if this requirement is missing in requirement file for the home-assistant/core?

**Comment by jmgiaever** [comment]
Also, have you connected the bluez interface?```snap connect home-assistant-snap:bluez```"The bluez interface | Snapcraft documentation" https://snapcraft.io/docs/bluez-interface

**Comment by jrohde** [comment]
Alright, i searched through some issues of the Core and it looks like the bluepy lib is somehow no longer included (it's commented out in requirements_all). So since this isn't a problem with HA Snap I'll close this issue. Thanks very much for looking in to it and the given suggestions. Now i know where to look first next time! 😃

**Comment by jmgiaever** [comment]
Hi,Yes. Seems like it was removed last year; https://github.com/home-assistant/core/search?q=bluepy&type=commitsIt's not very clear why, but I guess it broke HA on some architectures or operating systems. Have you tried to manually install bluepy? You should be able to log into the shell with `sudo snap run --shell home-assistant-snap` and ***enter the python venv***, and install it with pip. However it might lack some dependencies.
