### ISSUE TITLE
Nmap path not found

### ISSUE THREAD

**Issue by brunopiras** [home-assistant-snap/home-assistant-snap#20]
Hello there, 

I think there's a problem with Nmap, I've tried to remove and re-install more than one time but same issue:

`
Nmap scanning failed: 'nmap program was not found in path. PATH is : /snap/home-assistant-snap/533/usr/sbin:/snap/home-assistant-snap/533/usr/bin:/snap/home-assistant-snap/533/sbin:/snap/home-assistant-snap/533/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/home-assistant-snap/533/shared-bin/bin'
`
nmap it is installed on ubuntu:
`
nmap --version:
Nmap version 7.01 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.4 openssl-1.0.2g libpcre-8.44 libpcap-1.7.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
`
`
Whereis nmap:
nmap: /usr/bin/nmap /usr/local/sbin/nmap /usr/share/nmap /snap/bin/nmap /snap/bin/nmap.nping /snap/bin/nmap.ncat /usr/share/man/man1/nmap.1.gz
`

Thank you

**Comment by jmgiaever** [comment]
In which regard is nmap missing? 

The snap is running in a confined environment, so you can't access whatever you want in your system. And you can certainly not install it in the environment. 

Is nmap a requirement for an integration? Which, in that case?

Try to explain how what you're doing and trying to accomplish. It might be that you have to request it for the snap home-assistant-toolbox.

**Comment by brunopiras** [comment]
Hi, thanks to helping me,
I'm referring to home assistant, I've add nmap integration, normally integration from home assistant, but it does not works. Toolbox it's only for curl.

Thanks 🙏

**Comment by jmgiaever** [comment]
Ah, then it's part of the core and it should be added to this package. I'll add it for the next build.

**Comment by jmgiaever** [comment]
> Toolbox it's only for curl
PS! That's not true. It's for everything extra that isn't required by the core. But I can't include every possible extra binary, so whatever people need extra can be added to the toolbox 🧰

But in this case it's a core dependency.

**Comment by jmgiaever** [comment]
Nmap is now part of the core, in the `--channel=latest/stable`

**Comment by brunopiras** [comment]
Awesome, 

now:
![image](https://user-images.githubusercontent.com/55226575/202627141-250a002e-dcf4-4034-9571-52c193bf7e69.jpeg)

🤙
Thanks
