### ISSUE TITLE
platform commandline not supported by snap installation?

### ISSUE THREAD

**Issue by jjlacrampe** [home-assistant-snap/home-assistant-snap#21]
Hello, I want to use the commandline platform; to improve it I used an example given in the official documentation : https://www.home-assistant.io/integrations/switch.command_line/
--------------------------------------------------------------
# Example configuration.yaml entry
switch:
  - platform: command_line
    switches:
      home_assistant_system_shutdown:
        command_off: "/usr/sbin/poweroff
---------------------------------------------------------------
Sadly it fails :
![image](https://user-images.githubusercontent.com/46439070/201516064-57e4cfa7-31ba-4f4f-8ec4-54e49997456a.png)

Any suggestion?

**Comment by jmgiaever** [comment]
Hi,

The snap is confined, and you don't have access to everything in you OS. 

You can either request this binary for the home assistant toolbox, or install the app as `--classic` (flag).

**Comment by jjlacrampe** [comment]
Thanx for your suggestion, before installing a classic version of this snap, I have three questions
- is the classic version equivalent to a core version and can it be supervised?
- should I first remove the current confined version?
- If, before removing the confined version I keep a backup, is it possible to restore the configuration the newly installed classic version?
Sorry to solicit you so much but I did not find answers by googling!

**Comment by jmgiaever** [comment]
There's nothing as a "classic version". You simply just install it differently. https://snapcraft.io/docs/snap-confinement

I guess you have to remove the currently installed version, yes. I have never used classic confinement. 

If you have configurations that you want to keep, you should backup the content in `/var/snap/home-assistant-snap/current/` (might be different if you're not on Ubuntu) and restore them in this location after the new install.
