### ISSUE TITLE
Tibber has migrated to new endpoint

### ISSUE THREAD

**Issue by owanvik** [home-assistant-snap/home-assistant-snap#22]
Home Assistant 2022.11 and earlier is no longer supported.
Tibber switched off the websocket server at api.tibber.com
Home Assistant 2022.12 or later should work.

[Tibber Status report](https://status.tibber.com/incidents/fkh9ml637jf1)

**Comment by jmgiaever** [comment]
Hi,

Sorry, I've been super busy with work and personal stuff lately, and haven't had time to follow. 

I requested tracks for them yesterday, but they aren't created yet. I think 2022.11 is in latest though.
