### ISSUE TITLE
Only old versions available

### ISSUE THREAD

**Issue by kmifka** [home-assistant-snap/home-assistant-snap#23]
When I run `snap info home-assistant-snap`.
It only shows versions up to 2021... and I can't install newer versions either....

![Bildschirm­foto 2023-01-19 um 20 03 33](https://user-images.githubusercontent.com/24428910/213536809-072a9491-1692-46ce-b108-f98f363a997c.png)

Does anyone have any ideas?

**Comment by jmgiaever** [comment]
Very old 🤪

As long as I'm the only maintainer I'm only pushing latest to the `latest` track, and the final versions for each when they have hit final (aka "stable"). 

However the latest is typically in the edge channel (`latest/edge`).

**Comment by jmgiaever** [comment]
(ah, you're on armhf. We've ended support for those. Get a 64-bit OS and you'll get newer)

**Comment by kmifka** [comment]
Oh, you are right. Thanks for your fast reply :)

**Comment by jmgiaever** [comment]
Happy to help 😄 Hope you'll solve it!
