### ISSUE TITLE
Text labels are missing in configuration dialogs 

### ISSUE THREAD

**Issue by simba-tlk** [home-assistant-snap/home-assistant-snap#25]
Text labels are missing in configuration dialog when adding integrations.

Similar issue is described here:
https://community.home-assistant.io/t/the-text-labels-are-missing-in-the-mqtt-configuration-dialog/563808

It looks like the problem was sorted out in this post:
https://community.home-assistant.io/t/the-text-labels-are-missing-in-the-mqtt-configuration-dialog/563808/23

It would be great if this could be fixed in the snap release of home assistant. :)

**Comment by jmgiaever** [comment]
Dude, thank you so much for reporting this. This has bothered me so much! I will look into the fix ASAP

**Comment by jmgiaever** [comment]
Hi,
I think (hope) this will be fixed in the release that is currently building. It should be available in the edge channel within an hour time.

**Comment by jmgiaever** [comment]
Seems to be fixed. Closing this, re-open if I'm wrong.

**Comment by simba-tlk** [comment]
Text labels in configuration dialogs are now working fine! 

I now get invalid config with these error messages:

Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: cloud, mobile_app')
18:08:15 – (ERROR) setup.py
Unable to set up dependencies of default_config. Setup failed for dependencies: cloud, mobile_app
18:08:15 – (ERROR) setup.py
Setup failed for cloud: Unable to import component: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/snap/home-assistant-snap/568/lib/python3.11/site-packages/urllib3/util/ssl_.py)
18:08:14 – (ERROR) setup.py - message first occurred at 18:08:07 and shows up 2 times

Any clue how to fix? :)

**Comment by jmgiaever** [comment]
Nope, not at this moment. But I hope it's related to the earlier usage of `local-resolver`, whivh is removed. It's released for `amd64`. If you use it, you can refresh again and see if it resolved it. If not you have to wait for the `arm64` build, which takes about 45 min longer.

**Comment by jmgiaever** [comment]
> Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: cloud, mobile_app')
> 18:08:15 – (ERROR) setup.py
> Unable to set up dependencies of default_config. Setup failed for dependencies: cloud, mobile_app
> 18:08:15 – (ERROR) setup.py
> Setup failed for cloud: Unable to import component: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/snap/home-assistant-snap/568/lib/python3.11/site-packages/urllib3/util/ssl_.py)
> 18:08:14 – (ERROR) setup.py - message first occurred at 18:08:07 and shows up 2 times

However, there was an actual [issue related to this](https://github.com/home-assistant/core/issues/94239), which they claim should be [fixed with `2023.6.3`](https://github.com/home-assistant/core/pull/94587). It might be that they didn't manage to fix it.

If you have time, feel free to ask in the issue if the latest fixes fixed it for them.

**Comment by simba-tlk** [comment]
Problem went away on refreshing - thanks a lot! :)

**Comment by jmgiaever** [comment]
Great. Good to know, as I have `arm64` and haven't a release to test with yet. Hope it fixes it for me too. The new build also uses `python 3.11`, and not `3.10`.
