### ISSUE TITLE
2024.4.4 killed SkyConnect

### ISSUE THREAD

**Issue by owanvik** [home-assistant-snap/home-assistant-snap#31]
Updating to 2024.4.4 killed SkyConnect ZHA.
Rollback worked. I'll update again and check logs

**Comment by jmgiaever** [comment]
Hi, 

Do you have any startup logs? Is this a HACS integration?

Can you see any log entries about an installation that has failed?

**Comment by owanvik** [comment]
Reloading the ZHA-integration gives this:

`Logger: homeassistant
Kilde: /snap/home-assistant-snap/600/lib/python3.12/site-packages/homeassistant/runner.py:146
Førs oppstått: 03:50:18 (530 hendelser)
Sist logget: 11:52:26

Error doing job: Exception in callback SerialTransport._read_ready()
ValueError: (3, None) is not a valid NcpResetCode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/serial_asyncio_fast/__init__.py", line 137, in _read_ready
    self._protocol.data_received(data)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 84, in data_received
    self.frame_received(frame)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 121, in frame_received
    self.error_frame_received(data)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 197, in error_frame_received
    error_code, version = self._get_error_code(data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 193, in _get_error_code
    return t.NcpResetCode(data[2]), data[1]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/types/basic.py", line 216, in __call__
    return super().__call__(value, names, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 1179, in __new__
    raise exc
  File "/usr/lib/python3.12/enum.py", line 1156, in __new__
    result = cls._missing_(value)
             ^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/types/basic.py", line 225, in _missing_
    new = int_type.__new__(cls, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'`

**Comment by owanvik** [comment]
Not a HACS integration. Home Assistants own zigbee gateway

**Comment by jmgiaever** [comment]
To me this looks like an issue with the HA code. There are no general changes to the snap package, except updated with the newest version of HA. 

Have you tried asking if this affects anyone else, and what installation method they're using?

**Comment by owanvik** [comment]
Might be. I see other people have the issue as well
https://community.home-assistant.io/t/zigbee-suddenly-stopped-working-failed-setup-will-retry/726612

**Comment by jmgiaever** [comment]
From what I can see it's a [quite bit of a workaround](https://github.com/home-assistant/core/issues/115459#issuecomment-2072856136), which requires a temporary fix (actually a hack) just for this controller. 

It's obviously scheduled a fix in the 2024.5 release, so I suggest not doing anything in the snap, as it could cause other issues, but wait for the core team to fix it. 

https://github.com/home-assistant/core/issues/115459#issuecomment-2075689248

(PS! Yes, I know .5 is out now, but I don't have time for rolling releases of patch versions at the moment. Only minor = monthly. So I'll always wait until the last patch before doing anything, but if you want to give it a try then I can build a 2024.5.x for you).

**Comment by owanvik** [comment]
Yeah, i think waiting for .5 is the best option

**Comment by jmgiaever** [comment]
I've started a build for 2024.5.2 which should be available in the `latest/edge` track in an hour or so. 

You can switch track with

`sudo snap switch home-assistant-snap --channel latest/edge`

Followed by a `sudo snap refresh home-assistant-snap` when you can see the version available in that channel from `snap info home-assistant-snap `
