### ISSUE TITLE
Python 3.8 will be deprecated

### ISSUE THREAD

**Issue by hofst** [home-assistant-snap/home-assistant-snap#5]
I got this message after the last update:
<img width="357" alt="Capture" src="https://user-images.githubusercontent.com/2535762/140605703-9992551b-c7f8-47bf-a4d7-0fba332edd57.PNG">

I run homeassistant in full confinement and my system python version is 3.9, so I believe it must be referring to the snap's python version. I'm no expert in snaps, and don't know where to change the Python version.
I looked into: 
https://github.com/home-assistant-snap/home-assistant-snap/blob/master/snap/snapcraft.yaml
But see references to both python 3.8 and python 3.9.

**Comment by jmgiaever** [comment]
Hi @hofst 

It's correct that it's being deprecated, and the commented out «python 3.9» references you see is an attempt to bundle python3.9 with the snap. However that is not an easy task, and I haven't figured out *the way* of doing it. The debian package of Python3.9 seems to be missing `ensurepip`. I've tried so many ways of adding it manually, but it fails to compile then complaining about conflicting dependencies. 

However Python3.10 looks easier to bundle (I tried with the same method as I have for 3.9), so after 2-3 days of trail and errors with 3.9 I've decided to wait until 3.10. 

They announce in the release notes together with the announcement of deprecating 3.8 that they will get work on support for 3.10 before 3.8 is dropped.

I leave this open until it's resolved.

**Comment by hofst** [comment]
makes sense, thank you!

**Comment by hofst** [comment]
I just noticed another deprecation:
`2021-11-08 18:26:14 WARNING (Recorder) [homeassistant.components.recorder.util] Version 3.31.1 of SQLite is not supported; minimum supported version is 3.32.1. Starting with Home Assistant 2022.2 this will prevent the recorder from starting. Please upgrade your database software before then`

While the log message looks like it's only a warning, I also noticed that my `statistics` templates don't seem to work anymore which apparently rely on the recorder :(

**Comment by hofst** [comment]
Did some further debugging and it appears the recorder problem was some problem on my side.
But probably still a good idea to track the sqllite update so it doesn't break with 22.2 :-)

**Comment by jmgiaever** [comment]
Hi,

I think I've solved this now. New version is building and should be in `latest/edge` channel within some hours ~2 +/-

**Comment by jmgiaever** [comment]
Seems to be solved. If you're using HACS and get a notification about the missiong `aiogithubapi` just give it a restart and it should install the missing dependency.

**Comment by hofst** [comment]
Thanks a lot! :-)

**Comment by jmgiaever** [comment]
Happy to help. 😃
