### ISSUE TITLE
How to make backup?

### ISSUE THREAD

**Issue by lucasan123** [home-assistant-snap/home-assistant-snap#7]
Cannot make a backup of my configuration , so when I have to take away the machine , I cannot just load the snapshot backup from a file but I will have to do again from the beginning

**Comment by jmgiaever** [comment]
Not sure what you mean with "take away the machine"? Why would you "take it away"?

I need to know more details on your OS to help you with how you can backup. Your configuration is typically stored in `/var/snap/home-assistant-snap/current` 

If you're just re-installing the snap (but why would you?), then you can simply make a copy of this directory, e.g with `rsync`. 

If you're using Ubuntu Core, then you should use `snap snapshots`. But they're probably "gone away" if you're taking your machine away. 🤪

**Comment by lucasan123** [comment]
> Not sure what you mean with "take away the machine"? Why would you "take it away"?
> 
> I need to know more details on your OS to help you with how you can backup. Your configuration is typically stored in `/var/snap/home-assistant-snap/current`
> 
> If you're just re-installing the snap (but why would you?), then you can simply make a copy of this directory, e.g with `rsync`.
> 
> If you're using Ubuntu Core, then you should use `snap snapshots`. But they're probably "gone away" if you're taking your machine away. 🤪

My server sometimes dies suddendly and i dont know why. I think some components are faulty. So i have to move the homeassistant installation to another machine.
Not sure how to do this. i think i will install home assistant on a raspberry pi 3. Then how will i do to restore all the snapshots?

**Comment by jmgiaever** [comment]
What OS are you on now? And does you current machine still function? If so, just take a backup to your computer with `scp`

```
scp -R <user>@<my-ha-instance:IP>:/var/snap/home-assistant-snap/current ~/ha-backup
```
(You can use this method from anywhere having `scp` available to pull a backup, e.g with a `crontab`).

then push it to the new instance with

```
scp -R ~/ha-backup/* <user>@<my-new-ha-instance:IP>:/var/snap/home-assistant-snap/current 
```

Make sure that you have installed the snap on the new instance first, and I recommend that you stop it and clear the `current`-directory and wait to start it until the old backup is in place. :)

Hope it's helpful and explained good enough. But it's hard to know how your system works without any details.

**Comment by lucasan123** [comment]
> What OS are you on now? And does you current machine still function? If so, just take a backup to your computer with `scp`
> 
> ```
> scp -R <user>@<my-ha-instance:IP>:/var/snap/home-assistant-snap/current ~/ha-backup
> ```
> 
> (You can use this method from anywhere having `scp` available to pull a backup, e.g with a `crontab`).
> 
> then push it to the new instance with
> 
> ```
> scp -R ~/ha-backup/* <user>@<my-new-ha-instance:IP>:/var/snap/home-assistant-snap/current 
> ```
> 
> Make sure that you have installed the snap on the new instance first, and I recommend that you stop it and clear the `current`-directory and wait to start it until the old backup is in place. :)
> 
> Hope it's helpful and explained good enough. But it's hard to know how your system works without any details.

Im on ubuntu 18,04. Yes i can do the backup turning on the machine. 
Thanks you for the solution!

**Comment by jmgiaever** [comment]
Happy to help. Closing for now, feel free to re-open. :) Happy New Year!
