### ISSUE TITLE
Redundant mention of plugs in snapcraft.yaml

### ISSUE THREAD

**Issue by guyluz11** [home-assistant-snap/home-assistant-snap#8]
Both `network` and `network-bind` plugs are redundant as they are automatically being connected.

https://github.com/home-assistant-snap/home-assistant-snap/blob/e8d995a4be09bd4cfca51daaac422fdd71ea5706/snap/snapcraft.yaml#L132

![Screenshot_20220110-190745_Firefox](https://user-images.githubusercontent.com/9304740/148807872-b6f2eb41-4b4c-481c-acb7-fc98b95b878f.jpg)

**Comment by jmgiaever** [comment]
Hi, yes, you are right. Those are redundant. I chose to explain them when I requested auto-connection of `network-observe`. However these two are not special in the same way and quite self-explanatory. I've removed them. It will be live in the next release. :)
