### ISSUE TITLE
bluetooth support

### ISSUE THREAD

**Issue by edestecd** [home-assistant-snap/home-assistant-snap#9]
I have tried to enable several bluetooth integrations to no avail. I have tried the following three
https://www.home-assistant.io/integrations/bluetooth_tracker/
https://www.home-assistant.io/integrations/bluetooth_le_tracker/
https://github.com/spbrogan/sensor.mopeka_pro_check

The first requires pybluez. Home Assistant tries to install it but errors out needing gcc. I modified home-assistant-toolbox heavily to include gcc and link up all the libraries but eventually it was too much and I gave up.

bluetooth_le_tracker and mopeka_pro_check complain about not being able to connect to the bluetooth socket so i'm assuming python was not built with bluetooth support. They seem to want to use hcitool which is not available if i get a shell in the snap.

I should also mention that I tried enabling the bluez plug as well as installing the snap in devmode. Both were unsuccessful.

I just switched over to the official docker image and it seems to work. I'm just wondering what we are missing in the snap. I really enjoy using the snap as its much easier to setup than docker/vm etc.

**Comment by edestecd** [comment]
the docker image has hcitool and bluetooth/bluez installed in the container and its running in privileged mode which allows it to interact with the bluetooth hardware directly. This is how I understand it to be working

**Comment by jmgiaever** [comment]
Hi,

Sorry for my delayed response. I don't have any BLE devices at the moment, and therefor not tried these integrations. However I guess they are failing when you're adding the integrations so I can have a look at it. 

I saw that you cloned the toolbox. I'll have a look at it and checks if it's something that I can fix :) I'll keep you posted :)

**Comment by jmgiaever** [comment]
Hi again,

I've added the missing packages. Can you push your changes of the `home-assistant-toolbox` to your fork so I can see what you've done so far? I can only find that you've added the `bin`-file that references the curl binary.

**Comment by jmgiaever** [comment]
PS! The new build will be in the `latest/edge` channel, with revision 475+ depending on your architecture.

**Comment by jmgiaever** [comment]
I seem to have fixed this now. The `toolbox` is currently building and will be available in the `latest/edge` channel. You need revision `475` of Home Assistant for this to work, since that contains the Bluetooth dependencies. This is already now available in the channels `latest/stable` and `2021.12/stable` (recommended for controlled updates). 

To switch channel:

```
sudo snap switch <snap name> --channel=<channel>
sudo snap refresh <snap name>
```

Please test and report back. Closing this. Feel free to re-open.

**Comment by edestecd** [comment]
I pushed my changes to `home-assistant-toolbox` if you want to compare. I was stuck on `ld` not wanting to use libs from the snap.

**Comment by edestecd** [comment]
Thank you for working on this! I will give it a go soon and report back

**Comment by jmgiaever** [comment]
Great :) Looking forward to hear from you :) Hope it works! :)
